### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by wangbaobaoget** [Huelse/SEAL-Python#59] opened 2021-05-17 07:49 UTC
![image](https://user-images.githubusercontent.com/55700463/118451050-6883ae80-b727-11eb-950a-50f2b2a44e42.png)

**Comment by Huelse** [comment] 2021-05-17 15:02
This kind of error, you should understand by yourself, it's may be caused by the low version of cmake.

**Comment by Huelse** [comment] 2021-05-20 12:57
If no more problem, close this issue please.

**Comment by wangbaobaoget** [comment] 2021-05-21 01:13
my version of cmake is 3.12.2

**Closed** 2021-05-21 01:13 UTC
Labels: help wanted
