### ISSUE TITLE
python3 setup.py build_ext -i

### ISSUE THREAD

**Issue by qxzhou1010** [Huelse/SEAL-Python#32] opened 2020-06-18 01:42 UTC
Hi, I followed the Linux installation instructions step by step, then I tried to run the files under the tests folder, and an error was reported.
_**root@1be2fda826a0:/workspace/SEAL-Python/tests# python3 0_data_type.py
Traceback (most recent call last):
  File "0_data_type.py", line 1, in <module>
    from seal import *
ImportError: /workspace/SEAL-Python/tests/seal.cpython-37m-x86_64-linux-gnu.so: undefined symbol: deflateInit_**_
Then, I try to use the first solution of FAQ, but another error occured:
the SEAL_LIB_BUILD_TYPE=Shared don't exist.
Please help me!

**Comment by Huelse** [comment] 2020-06-18 06:15
It seems that you are building in docker, what about try to use the `build_docker.sh` ?
Or just try to build in your native environment

**Comment by Huelse** [comment] 2020-06-18 06:23
In `SEAL/native/src` to run the `cmake . -D SEAL_LIB_BUILD_TYPE=Shared`,
or change the `Static_PIC` to `Shared` in `SEAL/native/src/CMakeLists.txt` line 101

**Comment by qxzhou1010** [comment] 2020-06-18 06:47
I  changed the Static_PIC to Shared in SEAL/native/src/CMakeLists.txt line 101
**Library build type (SEAL_LIB_BUILD_TYPE): Shared**
However, another error occured:
_**(base) root@1be2fda826a0:/workspace/SEAL-Python# python3 setup.py install
Can not find the seal lib
(base) root@1be2fda826a0:/workspace/SEAL-Python# python3 setup.py install
Can not find the seal lib
(base) root@1be2fda826a0:/workspace/SEAL-Python# python3 setup.py build_ext -i
Can not find the seal lib**_

**Comment by Huelse** [comment] 2020-06-18 06:53
change the path in `setup.py` line 15,
I mentioned it in the FAQ.

**Comment by Huelse** [comment] 2020-06-18 09:29
If you have no problem, please close this issue.

**Comment by DreamingRaven** [comment] 2020-06-23 14:12
Hey @qxzhou1010  I think its *either* that the seal lib has not been built properly (its not shared by default I dont think), or your system does not know where to find it. Some systems like mine (archlinux) look in different folders to other distros, you may need to add it if you can manually find where the file has been installed to. You may want to take a look at where I had a similar ish problem before of not finding the seal lib: https://github.com/Huelse/SEAL-Python/issues/14

 I also have applied these patches to my own fork since I need them as shared objects .so permenantley: https://github.com/Huelse/SEAL-Python/compare/master...DreamingRaven:3.4.5-rlatest

As for docker, I have confirmed that the docker container works as it should, so there should not be any problem there if you want to try that out too. Containers are super usefull for reproducing stuff like this, and in the Dockerfile outline a step by step of how the image is created so it is kind of its own instruction manual too.

However like Huelse says, if you have already solved the problem, please do post it here and close the issue so others can benefit from your experience. Cheers and all the best.

**Closed** 2021-04-13 01:38 UTC
